### ISSUE TITLE
cannot submit for task 2

### ISSUE THREAD

**Issue by sdx0112** [discoverychallenge/dc-evaluator-2016#1]
There is no reaction when I submit my solution to task 2.

**Comment by discoverychallenge** [comment]
Hi, I can clearly see you on the public leaderboard. What do you exactly mean on "no reaction"?

**Comment by sdx0112** [comment]
I can see it also after 10 mins of my submission. And in my "team submission" tab, it says I have one submission for Task 1, not Task 2.

**Comment by discoverychallenge** [comment]
Ok, thank you for the feedback,  we will investigate this, and return to you soon!

**Comment by frederickayala** [comment]
Hi @sdx0112, thanks for reporting the issue.

I fixed the "team submission" tab. The problem was the title of the section. Now it should that your submission is for Task 2.

Let us know if you have any other issue.

Thanks!
