### ISSUE TITLE
Adding new member to team

### ISSUE THREAD

**Issue by ThakurRajAnand** [discoverychallenge/dc-evaluator-2016#10]
@frederickayala  How can we add new team members

**Comment by frederickayala** [comment]
Hi @ThakurRajAnand unfortunately you cannot have more then one login credential per team. You can share your login credentials with your team members. If you want to change your team name and password you can do this on the "Team Profile" page.

**Comment by ThakurRajAnand** [comment]
@frederickayala How will I add team members and how can we notify you guys how many team members we have in team.

**Comment by ThakurRajAnand** [comment]
@frederickayala I understand everyone can use same login but how can people see these are the team members of this team on Leaderboard.

**Comment by rpalovics** [comment]
@ThakurRajAnand we do not use any authentication or identification for the team members. The leaderboard only contains the team names. Team participants are then announced for the winner teams at the conference. We strongly ask the competitors not to participate in multiple teams. Hacking the 3 submissions/team limit by multiple accounts or by any other tries leads to automatic suspension. Is this helps? Tell me if we could not answer your question.

**Comment by ThakurRajAnand** [comment]
@rpalovics This was helpful. Closing this issue for now.
