### ISSUE TITLE
At what time does the clock for a new batch of submissions reset?

### ISSUE THREAD

**Issue by elleros** [discoverychallenge/dc-evaluator-2016#11]
The rules state: "Each team can upload a maximum 3 solutions per day."

How is the end time for the "submission day" defined? Is it defined according to a specific time zone? Or relative to the time of the team's first submission?

Thank you.
Lorenzo

**Comment by frederickayala** [comment]
Hi @elleros we count the number of team submissions after UTC time - 24 hours. We allow teams to submit if they haven't reach the 3 submissions limit within this period.

**Comment by hamzame1** [comment]
Hello,
Please can we use another language over python
