### ISSUE TITLE
Score for Task 1 hasn't been calculated

### ISSUE THREAD

**Issue by TiborSzabo42** [discoverychallenge/dc-evaluator-2016#12]
Hello! 

I (from Degrees of Freedom) have uploaded a submission for Task 1 but I can't see its score and I haven't received any error message. Is there any problem with my solution format? Could you please check it?

Thanks in advance!
Tibi

**Comment by frederickayala** [comment]
Hi @TiborSzabo42 

I checked the database and your last team's submission for task 1 was on 2016-05-04.

I guess an error occurred while uploading your submission. Could you upload it again? Let me know if you are still having this issue.

Thanks for reporting.

Fred

**Comment by TiborSzabo42** [comment]
Thank you for your answer! I have had no opportunity to try uploading it again so far (because of my limited internet access) but soon I definitely will try it again, thanks!

Tibi

**Comment by TiborSzabo42** [comment]
I succesfully uploaded it. The problem was that you mentioned. Thanks!

Tibi
