### ISSUE TITLE
final submission

### ISSUE THREAD

**Issue by paljenczy** [discoverychallenge/dc-evaluator-2016#13]
What is the rule for final evaluation? How can participants control which submission to evaluate as the final model?

**Comment by frederickayala** [comment]
Hi @paljenczy. You can make 3 submissions per task per day (UTC time). At the end we will take the best score of any of your submissions.

**Comment by paljenczy** [comment]
So am I right that all submissions are stored, all of them are evaluated and the best is chosen, regardless of the public score of the individual submissions?

**Comment by frederickayala** [comment]
@paljenczy The public leaderboard shows the team's best score using just 30% of the testing labels. The final evaluation will take the best team score using 100% of the testing labels.

**Comment by paljenczy** [comment]
OK, thanks!
