### ISSUE TITLE
Test data already has credit card users

### ISSUE THREAD

**Issue by suresh-chinta** [discoverychallenge/dc-evaluator-2016#14]
Hello,

The test data for the first half of 2015 has credit card transactions, which means some of the users already have credit cards.

When we say the prediction should be for the second half of the year, will it be possible to apply for second credit card by a user who already has a credit card from the bank ?

Is it correct to assume that the users who have made CC transactions are using this Bank's CC.

Thanks,
Suresh

**Comment by rpalovics** [comment]
Hi,

yes, it is possible to apply for another credit card. You can assume that all the cards are from this bank.

Best,

Robi

**Comment by krz** [comment]
Hi,

I have one question regarding this as well: In the 2014 train data (`TARGET_TASK_2` variable) we have people applying for a credit card in 2015. Some people as late as October 2015.
When predicting the 2015 data, to which time span extends the date there? Only 2015, or beyond, as in the train data?

And is there a specific reason each date is set to the last day of the month?

thanks

**Comment by rpalovics** [comment]
Hi,

1 Good observation about the dates: we intentionally left application dates that are from 2015 for users in the 2014 training data. It is your choice to include this information in your models or to discard it.

2 For the 2015 users, application dates come only from 2015 in the test.

3 There is no specific reason for the "last day of the month" observation.
