### ISSUE TITLE
Cannot submit task 2

### ISSUE THREAD

**Issue by ZEMUSHKA** [discoverychallenge/dc-evaluator-2016#17]
It looks like it uploads the solution, then there's a grey popup without text and nothing happens.

**Comment by molnarpeter** [comment]
Hi 
We have problems with the submission as well. It seems that the file is uploaded and evaluated but it can not be seen on the submission page...

**Comment by marugari** [comment]
Will deadlines change?

**Comment by gauravsc** [comment]
Same issue, a grey box appears. Unable to get the submission evaluated for the entire day.

**Comment by frederickayala** [comment]
Hi guys, I am checking the problem. I will come soon with news

**Comment by frederickayala** [comment]
Hi @gauravsc @marugari @molnarpeter @ZEMUSHKA, could you please try to submit your solutions again? Let me know if you were able to submit the file.

**Comment by marugari** [comment]
I have submitted.
