### ISSUE TITLE
Problem: cannot download the datasets

### ISSUE THREAD

**Issue by Cherishzhang** [discoverychallenge/dc-evaluator-2016#3]
I have been approved.
I use Chrome to open the download dataset page. It shows me "please wait for the download to finish". But nothing to be download in Chrome after a few seconds.

**Comment by frederickayala** [comment]
Hi, 

Maybe the download is being timed out by our server. Could you please tell me your internet speed connection?

I will try increasing the request timeout. We are checking the issue. Thanks for reporting.

Fred

**Comment by Cherishzhang** [comment]
From the Chrome console, It show me "**GET https://dms.sztaki.hu/ecml-pkkd-2016/Team/getFile/ net::ERR_CONTENT_LENGTH_MISMATCH**"
The internet speed is 100.0 Mbps

**Comment by frederickayala** [comment]
Hi, with that speed there shouldn't be any problem :) I restarted the Web Server. Could you please clear your browser cache and try again? Maybe try in an incognito window.

**Comment by Cherishzhang** [comment]
Thanks for your help @frederickayala, but I still cannot download the datasets. May be some problem are in the internet connection.
