### ISSUE TITLE
About Geolocation Information?

### ISSUE THREAD

**Issue by JasonRui** [discoverychallenge/dc-evaluator-2016#4]
I consume that GEO_X is the latitude and GEO_Y is the longitude. 
The "664808 244104" means the latitude is 66.4808 and the longitude is 24.4104. There is a problem that the latitude can be 85.9443 and couldn't find the place. Is that I am wrong in interpreting the Geolocation information?

**Comment by discoverychallenge** [comment]
This is supposed to be anonymized data - it is not disallowed to plot it, but unfortunately we cannot give more information about the coordinates.
