### ISSUE TITLE
Submisson 1 column names

### ISSUE THREAD

**Issue by adamszakal91** [discoverychallenge/dc-evaluator-2016#5]
Dear Organizers,

I cannot find any information about the csv structure of first submission, can you share the file format information or give us an example submission file?

Thanks,
Ádám

**Comment by discoverychallenge** [comment]
Hi,

check out the submission format section at the dataset page:
https://dms.sztaki.hu/ecml-pkkd-2016/#/app/datasets  

Best,

Robi

**Comment by adamszakal91** [comment]
Thank you, I missed to scroll enough deep.
