### ISSUE TITLE
How long does it take for evaluation?

### ISSUE THREAD

**Issue by vinhqdang** [discoverychallenge/dc-evaluator-2016#6]
Hello

I submitted a submission several hours ago, and still now it is in evaluation. Usually how does it take for evaluation?

Thanks

**Comment by frederickayala** [comment]
Hi @vinhqdang , the evaluation should take some minutes. I run the evaluation for your submission. I am checking the reasons why it was not automatically evaluated. Thanks for reporting the issue.

**Comment by vinhqdang** [comment]
Hello

No problem. Thanks for your answer.

**Comment by wistuba** [comment]
Hi everyone,
I am facing currently the same problem. Evaluation is now in progress for a couple of hours.
Thanks for your help.

**Comment by frederickayala** [comment]
@wistuba ups... sorry about that. I manually run the evaluation for your submission. I will add a periodic task to fix this issue. Thanks for reporting the issue.

**Comment by ThakurRajAnand** [comment]
I am also facing the same issue and evaluation has been running for 2 of my submission from last 10 hours. My first submission got evaluated in 2 minutes. Can you please evaluate them.

**Comment by frederickayala** [comment]
Hi @ThakurRajAnand done. Today I am working to solve this issue (finally) :)

**Comment by ThakurRajAnand** [comment]
Thanks @frederickayala :)

**Comment by ThakurRajAnand** [comment]
Please evaluate my recent submission if possible @frederickayala

**Comment by frederickayala** [comment]
I changed the code. Please report if you have any problem with further submissions. Thanks.

**Comment by ThakurRajAnand** [comment]
@frederickayala I am again facing the same issue. Actually,  now I can't  see anything happening after clicking on submit. Can you please look into the issue.

**Comment by frederickayala** [comment]
Hi @ThakurRajAnand do you see the message "Uploading and evaluating the submission, please wait."? If not, can you clear the cache of your browser and reload the application?  ![screen shot 2016-04-22 at 2 00 50 pm](https://cloud.githubusercontent.com/assets/6177952/14740903/b7b68354-0892-11e6-988f-0c179d7a3c62.png)

**Comment by frederickayala** [comment]
Hi @ThakurRajAnand could you make your submission?

**Comment by ThakurRajAnand** [comment]
@frederickayala I apologise for not replying. I was away for couple of days and missed your message. I was able to make submission after clearing cache as per your recommendation

**Comment by frederickayala** [comment]
@ThakurRajAnand no problem :) let me know if you have any other issue.
