### ISSUE TITLE
Can not download the dataset?

### ISSUE THREAD

**Issue by rraabb** [discoverychallenge/dc-evaluator-2016#8]
I tried several times, the pages shows "There was an error while downloading the file. Please try again"

How can I solve this problem? Thanks!

**Comment by frederickayala** [comment]
Hi @rraabb could you please do the following:

- Open the Chrome Developer Tools
- Go to the Network tab and then click on the "XHR" button
- Go to the Discovery Challenge website and start downloading the dataset
- A row will appear showing the address "https://dms.sztaki.hu/ecml-pkkd-2016/Team/getFile/"

Could you please tell me what does the the Size Content and Time Latency say? Also, could you please send me the text that appears on the Headers tab?

Thanks! This will help me to understand what's going on.

**Comment by frederickayala** [comment]
Hi @rraabb I couldn't find your team. Could you please tell me your username? I will send you an e-mail with instructions on how to download the dataset.

**Comment by frederickayala** [comment]
@rraabb please clear the cache of your browser, refresh the website and try to download the dataset. If the download fails further instructions to download the file via FTP are given.

**Comment by rraabb** [comment]
@frederickayala  downloaded  sucessfully using the FTP, , thanks:)
