### ISSUE TITLE
I cannot download the dataset

### ISSUE THREAD

**Issue by aminsadri** [discoverychallenge/dc-evaluator-2016#9]
I tried several times but it did not work.

I also used IE. It downloaded the dataset but the file was broken.

**Comment by aminsadri** [comment]
With Chrome it says "There was an error while downloading the file. Please try again."

**Comment by frederickayala** [comment]
Hi @aminsadri could you please do the following:

Open the Chrome Developer Tools
Go to the Network tab and then click on the "XHR" button
Go to the Discovery Challenge website and start downloading the dataset
A row will appear showing the address "https://dms.sztaki.hu/ecml-pkkd-2016/Team/getFile/"
Could you please tell me what does the the Size Content and Time Latency say? Also, could you please send me the text that appears on the Headers tab?

Thanks! This will help me to understand what's going on.

**Comment by wiemsalah** [comment]
hi 
when i try to dowload dataset the page show me error message "There was an error while downloading the file. Please try again"
i try to follow the instructions: 
Go to the Network tab and then click on the "XHR" button
Go to the Discovery Challenge website and start downloading the dataset
A row will appear showing the address "https://dms.sztaki.hu/ecml-pkkd-2016/Team/getFile/"
but google show the same error.

**Comment by frederickayala** [comment]
@aminsadri @wiemsalah please clear the cache of your browser and refresh the website. Then, try again to download the dataset. I added instructions on how to download the dataset via FTP after the error occurs.

**Comment by wiemsalah** [comment]
the page show me this error : Unable to login with the credentials provided

**Comment by frederickayala** [comment]
@wiemsalah you should download the file via the website https://dms.sztaki.hu/ecml-pkkd-2016/

**Comment by wiemsalah** [comment]
@frederickayala yes i try to dowload it from the website ; https://dms.sztaki.hu/ecml-pkkd-2016/ 
i received this error : Unable to login with the credentials provided

**Comment by frederickayala** [comment]
@wiemsalah is your username and password correct?

**Comment by wiemsalah** [comment]
@frederickayala  yes i'll try again

**Comment by frederickayala** [comment]
@wiemsalah what's your username I can reset your password if you want and send it to the registered e-mail

**Comment by wiemsalah** [comment]
the page show : Try to download the dataset via our FTP server
Server: info.ilab.sztaki.hu 
Username: ecml 
Password: 3uiefj42ldf

**Comment by frederickayala** [comment]
@wiemsalah use those credentials to download the file via a FTP client like https://filezilla-project.org/

**Comment by wiemsalah** [comment]
i received this error : Connecting to server info.ilab.sztaki.hu:14147...
Trying to reconnect in 5 seconds
Error: Connection to server lost...

**Comment by frederickayala** [comment]
@wiemsalah you shouldn't be connecting to port 14147. Follow this tutorial on how to connect to a FTP Server: https://wiki.filezilla-project.org/FileZilla_Client_Tutorial_(en)

**Comment by wiemsalah** [comment]
hi  
thanks it works correctly
